export * from "./Hero";
export * from "./About";
export * from "./Facilities";
export * from "./OtherFeatures";
export * from "./ContactForm";
export * from "./Testimonials";
export * from "./Newsletter";
export * from "./Footer";
export * from "./Navbar";
